config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :delivery_burden
  belongs_to_active_hash :shipment_source
  belongs_to_active_hash :day_to_ship
  belongs_to :user
  has_one :order
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :description
    validates :category_id, numericality: { other_than: 1 }
    validates :status_id, numericality: { other_than: 1 }
    validates :delivery_burden_id, numericality: { other_than: 1 }
    validates :shipment_source_id, numericality: { other_than: 0 }
    validates :day_to_ship_id, numericality: { other_than: 1 }
    validates :price, numericality: { greater_than: 299, less_than: 10_000_000 }, format: { with: /\A[0-9]+\z/ }
    validates :image
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :sold_out_index, only: [:edit, :update, :destroy]
  def index
    @items = Item.all.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path(params[:id])
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(
      :image, :name, :description, :category_id, :status_id, :delivery_burden_id, :shipment_source_id, :day_to_ship_id, :price
    ).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? && current_user.id == @item.user.id
  end
end

def sold_out_index
  redirect_to root_path if @item.order
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
%body
  .items-sell-contents
    %header.items-sell-header
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
    .items-sell-main
      %h2.items-sell-title 商品の情報を入力
      = form_with model: @item, local: true do |f|
        = render 'shared/error_messages', model: f.object
        .img-upload
          .weight-bold-text
            出品画像
            %span.indispensable 必須
          .click-upload
            %p
              クリックしてファイルをアップロード
            = f.file_field :image, id:"item-image"
        .new-items
          .weight-bold-text
            商品名
            %span.indispensable 必須
          = f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40"
          .items-explain
            .weight-bold-text
              商品の説明
              %span.indispensable 必須
            = f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000"
        .items-detail
          .weight-bold-text 商品の詳細
          .form
            .weight-bold-text
              カテゴリー
              %span.indispensable 必須
            = f.collection_select(:category_id, Category.all, :id, :category, {}, {class:"select-box", id:"item-category"})
            .weight-bold-text
              商品の状態
              %span.indispensable 必須
            = f.collection_select(:status_id, Status.all, :id, :status, {}, {class:"select-box", id:"item-sales-status"})
        .items-detail
          .weight-bold-text.question-text
            %span 配送について
            %a.question{:href => "#"} ?
          .form
            .weight-bold-text
              配送料の負担
              %span.indispensable 必須
            = f.collection_select(:delivery_burden_id, DeliveryBurden.all, :id, :delivery_burden, {}, {class:"select-box", id:"item-shipping-fee-status"})
            .weight-bold-text
              発送元の地域
              %span.indispensable 必須
            = f.collection_select(:shipment_source_id, ShipmentSource.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"})
            .weight-bold-text
              発送までの日数
              %span.indispensable 必須
            = f.collection_select(:day_to_ship_id, DayToShip.all, :id, :day_to_ship, {}, {class:"select-box", id:"item-scheduled-delivery"})
        .sell-price
          .weight-bold-text.question-text
            %span
              販売価格
              %br>/
              (¥300〜9,999,999)
            %a.question{:href => "#"} ?
          %div
            .price-content
              .price-text
                %span 価格
                %span.indispensable 必須
              %span.sell-yen ¥
              = f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300"
            .price-content
              %span 販売手数料 (10%)
              %span
                %span#add-tax-price>
                円
            .price-content
              %span 販売利益
              %span
                %span#profit>
                円
        .caution
          %p.sentence
            %a{:href => "#"} 禁止されている出品、
            %a{:href => "#"} 行為
            を必ずご確認ください。
          %p.sentence
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            %a{:href => "#"} 偽ブランドの販売
            は犯罪であり処罰される可能性があります。
          %p.sentence
            また、出品をもちまして
            %a{:href => "#"} 加盟店規約
            に同意したことになります。
        .sell-btn-contents
          = f.submit "変更する" ,class:"sell-btn"
          = link_to 'もどる', item_path(@item.id), class:"back-btn"
    %footer.items-sell-footer
      %ul.menu
        %li
          %a{:href => "#"} プライバシーポリシー
        %li
          %a{:href => "#"} フリマ利用規約
        %li
          %a{:href => "#"} 特定商取引に関する表記
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
      %p.inc
        ©︎Furima,Inc.

app/views/items/index.html.haml
= render "shared/header"
.main
  .title-contents
    %h2.service-title.animate__animated.animate__fadeInTopLeft
      人生を変えるフリマアプリ
    %p.service-explain
      FURIMAはだれでもかんたんに出品・購入できる
    %p.service-explain.animate__animated.animate__fadeInTopLeft
      フリマアプリです
    .store-btn
      = link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#"
      = link_to image_tag("dl-android.png", class:"google-btn"), "#"
  .select-reason-contents
    %h2.title.animate__animated.animate__zoomInRight
      FURIMAが選ばれる3つの理由
    %ul.reason-lists
      %li.list
        = image_tag "furima-intro01.png", class:"list-pict"
        %span.reason-list-number 1
        %h3.reason-list-text
          %span.reason-list-blue-text 3分
          ですぐに出品
        %p.reason-list-description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        = image_tag "furima-intro02.png", class:"list-pict"
        %span.reason-list-number 2
        %h3.reason-list-text
          %span.reason-list-blue-text シンプル
          で使いやすい
        %p.reason-list-description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        = image_tag "furima-intro03.png", class:"list-pict"
        %span.reason-list-number 3
        %h3.reason-list-text
          手数料
          %span.reason-list-blue-text 業界最安
        %p.reason-list-description
          最大3%でお得に出品&amp;購入！
  .ad-contents
    %h2.ad-title
      会員数日本一位
    %p.ad-explain
      FURIMAは、フリマアプリで最も人気。
    %p.ad-explain
      出品・購入回数も業界最多です！
    %p.ad-explain
      ほしかったあの商品に出会えるかもしれません。
    .store-btn
      = link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#"
      = link_to image_tag("dl-android.png", class:"google-btn"), "#"
  .feature-contents
    %h2.title
      FURIMAの特徴
    %ul.feature-lists
      %li.list
        = image_tag "furima-intro04.png", class:"list-pict"
        %h3.feature-list-text
          簡単に売り買いできる
        %p.feature-list-description
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list
        = image_tag "furima-intro05.png", class:"list-pict"
        %h3.feature-list-text
          売上金は即日振込みに対応
        %p.feature-list-description
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
      %li.list
        = image_tag "furima-intro06.png", class:"list-pict"
        %h3.feature-list-text
          様々な支払いに対応
        %p.feature-list-description
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .item-contents
    %h2.title ピックアップカテゴリー
    = link_to '新規投稿商品', "#", class: "subtitle"
    %ul.item-lists
      - @items.each do |item|
        %li.list
          = link_to item_path(item.id) do
            .item-img-content
              = image_tag item.image, class: "item-img" if item.image.attached?
              - if item.order
                .sold-out
                  %span Sold Out!!
            .item-info
              %h3.item-name
                = item.name
              .item-price
                %span
                  = item.price
                  円
                  %br>/
                  (税込み)
                .star-btn
                  = image_tag "star.png", class:"star-icon"
                  %span.star-count 0
      - if @items.empty?
        %li.list
          = link_to '#' do
            = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img"
            .item-info
              %h3.item-name
                商品が
              .item-price
                %span
                  99999999円
                  %br>/
                  (税込み)
                .star-btn
                  = image_tag "star.png", class:"star-icon"
                  %span.star-count 0
- if user_signed_in?
  %a{:href => "/items/new"}
    .purchase-btn
      %span.purchase-btn-text 出品する
      = image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon"
- else
  %a{:href => "/users/sign_in"}
    .purchase-btn
      %span.purchase-btn-text 出品する
      = image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon"
= render "shared/footer"

app/views/items/new.html.haml
- provide(:title,"商品出品ページ")
%body
  .items-sell-contents
    %header.items-sell-header
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
    .items-sell-main
      %h2.items-sell-title 商品の情報を入力
      = form_with model: @item, local: true do |f|
        = render 'shared/error_messages', model: f.object
        .img-upload
          .weight-bold-text
            出品画像
            %span.indispensable 必須
          .click-upload
            %p
              クリックしてファイルをアップロード
            = f.file_field :image, id:"item-image"
        .new-items
          .weight-bold-text
            商品名
            %span.indispensable 必須
          = f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40"
          .items-explain
            .weight-bold-text
              商品の説明
              %span.indispensable 必須
            = f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000"
        .items-detail
          .weight-bold-text 商品の詳細
          .form
            .weight-bold-text
              カテゴリー
              %span.indispensable 必須
            = f.collection_select(:category_id, Category.all, :id, :category, {}, {class:"select-box", id:"item-category"})
            .weight-bold-text
              商品の状態
              %span.indispensable 必須
            = f.collection_select(:status_id, Status.all, :id, :status, {}, {class:"select-box", id:"item-sales-status"})
        .items-detail
          .weight-bold-text.question-text
            %span 配送について
            %a.question{:href => "#"} ?
          .form
            .weight-bold-text
              配送料の負担
              %span.indispensable 必須
            = f.collection_select(:delivery_burden_id, DeliveryBurden.all, :id, :delivery_burden, {}, {class:"select-box", id:"item-shipping-fee-status"})
            .weight-bold-text
              発送元の地域
              %span.indispensable 必須
            = f.collection_select(:shipment_source_id, ShipmentSource.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"})
            .weight-bold-text
              発送までの日数
              %span.indispensable 必須
            = f.collection_select(:day_to_ship_id, DayToShip.all, :id, :day_to_ship, {}, {class:"select-box", id:"item-scheduled-delivery"})
        .sell-price
          .weight-bold-text.question-text
            %span
              販売価格
              %br>/
              (¥300〜9,999,999)
            %a.question{:href => "#"} ?
          %div
            .price-content
              .price-text
                %span 価格
                %span.indispensable 必須
              %span.sell-yen ¥
              = f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300"
            .price-content
              %span 販売手数料 (10%)
              %span
                %span#add-tax-price>
                円
            .price-content
              %span 販売利益
              %span
                %span#profit>
                円
        .caution
          %p.sentence
            %a{:href => "#"} 禁止されている出品、
            %a{:href => "#"} 行為
            を必ずご確認ください。
          %p.sentence
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            %a{:href => "#"} 偽ブランドの販売
            は犯罪であり処罰される可能性があります。
          %p.sentence
            また、出品をもちまして
            %a{:href => "#"} 加盟店規約
            に同意したことになります。
        .sell-btn-contents
          = f.submit "出品する" ,class:"sell-btn"
          = link_to 'もどる', root_path, class:"back-btn"
    %footer.items-sell-footer
      %ul.menu
        %li
          %a{:href => "#"} プライバシーポリシー
        %li
          %a{:href => "#"} フリマ利用規約
        %li
          %a{:href => "#"} 特定商取引に関する表記
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
      %p.inc
        ©︎Furima,Inc.

app/views/items/show.html.haml
= render "shared/header"
.item-show
  .item-box
    %h2.name
      = @item.name
    .item-img-content
      = image_tag @item.image ,class:"item-box-img" if @item.image.attached?
      - if @item.order
        .sold-out
          %span Sold Out!!
    .item-price-box
      %span.item-price
        = "¥ #{@item.price}"
      %span.item-postage
        (税込) 送料込み
    - if user_signed_in? &&  current_user.id == @item.user.id
      - unless @item.order
        = link_to '商品の編集', edit_item_path(@item.id) , method: :get, class: "item-red-btn"
        %p.or-text or
        = link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy'
    - if user_signed_in? &&  current_user.id != @item.user.id
      - unless @item.order
        = link_to '購入画面に進む', item_orders_path(@item.id), class:"item-red-btn"
    .item-explain-box
      %span= @item.description
    %table.detail-table
      %tbody
        %tr
          %th.detail-item 出品者
          %td.detail-value= @item.user.nickname
        %tr
          %th.detail-item カテゴリー
          %td.detail-value= @item.category.category
        %tr
          %th.detail-item 商品の状態
          %td.detail-value= @item.status.status
        %tr
          %th.detail-item 配送料の負担
          %td.detail-value= @item.delivery_burden.delivery_burden
        %tr
          %th.detail-item 発送元の地域
          %td.detail-value= @item.shipment_source.name
        %tr
          %th.detail-item 発送日の目安
          %td.detail-value= @item.day_to_ship.day_to_ship
    .option
      .favorite-btn
        = image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"
        %span お気に入り 0
      .report-btn
        = image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"
        %span 不適切な商品の通報
  .comment-box
    %form
      %textarea.comment-text
      %p.comment-warn
        相手のことを考え丁寧なコメントを心がけましょう。
        %br/
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %button.comment-btn{:type => "submit"}
        = image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"
        %span
          コメントする
          %span
  .links
    %a.change-item-btn{:href => "#"}
      ＜ 前の商品
    %a.change-item-btn{:href => "#"}
      後ろの商品 ＞
  %a.another-item{:href => "#"}
    = @item.category.category
    をもっと見る
= render "shared/footer"